Repository GitHub-Campus-Experts-Unilag/DevZenBackend, pull requests merged in 2024-10, with the labels that each got.

#6 fixes #5, the swagger is now working, and remove user.password since …
  src/auth/services/sign.in.ts
  src/core/config/swagger.ts
Labels: hacktoberfest-accepted

#10 Chore/cleanup and arrange
  .env.example
  CONTRIBUTING.md
  README.md
  package-lock.json
  src/app/app.router.ts
  src/app/app.service.ts
  src/app/index.ts
  src/app/router/index.ts
  src/app/router/protected.ts
  src/auth/auth.module.ts
  src/auth/config/passport-config.ts
  src/auth/controllers/github.controller.ts
  src/auth/routes/index.ts
  src/auth/routes/signin.route.ts
  src/auth/services/google.ts
  src/auth/services/index.ts
  src/auth/services/passport/github.ts
  src/auth/services/passport/google.ts
  src/auth/services/passport/index.ts
  src/auth/services/sign.in.ts
  src/auth/strategies/passport-github.ts
  src/core/config/config.ts
  src/users/models/user.interface.ts
  src/users/models/users.schema.ts
  src/zenboard/index.ts
  src/zenboard/listeners/index.ts
  src/zenboard/models/index.ts
  src/zenboard/routes/index.ts
  src/zenboard/services/index.ts
  src/zenboard/utils/index.ts
  src/zenboard/utils/schema/index.ts
Labels: hacktoberfest

#15 Update README.md
  README.md
Labels: documentation, hacktoberfest
